#spring 相关配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imoocspringcloud?characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
person:
  name: lily
  age: 19
  sex: nv
